version: '3'

services:
  web:
    build: ./web
    # env_file: ./web/.env
    ports:
      - "5000:5000"
    environment:
      - DB_REMOTE=PROD
      - DEBUG=False
      - LOCAL=True
      - SLACK_BOT_TOKEN=xoxb-973594616288-2750447535381-mWwXC1qbeFb99uFjJ4SXWMtl
      - SLACK_WEBHOOK_GENERAL=https://hooks.slack.com/services/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
      - generalWebhook=https://hooks.slack.com/services/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
      - USAJOBS_API_KEY=TU37dsbsvSn6ICF6eh+mSYT70AA7r0gQdIaRBvZbmwc=
      - MONGO_URI=mongodb+srv://adminbirbs:sinQDyKvYWuDWFkX@cluster0.xgabv.mongodb.net/test
    # volumes:
    #   - ./web:/web
    # command: gunicorn --log-file=- --bind 0.0.0.0:5000 -k flask_sockets.worker run:app wsgi
    # depends_on:
    #   - "redis"
    # worker:
    #   build: ./web
    #   env_file: ./web/.env
    #   command: python3 worker.py
    #   depends_on:
    #     - "redis"
    #   dashboard:
    #     build: ./web
    #     env_file: ./web/.env
    #     ports:
    #       - "9181:9181"
    #     command: rq-dashboard
    #     depends_on:
    #       - "redis"
    # redis:
    #   image: redis:latest
    #   container_name: redis
    #   command: sh -c "rm -f /data/dump.rdb && redis-server" # disable persistence
    #   ports:
    #     - "6379:6379"
    # clock:
    #   build: ./web
    #   env_file: ./web/.env
    #   command: python3 clock.py
    #   depends_on:
    #     - "redis"
