version: '3'

services:
  web:
    build: ./web
    env_file: ./web/.env
    ports:
      - "5000:5000"
    # volumes:
    #   - ./web:/web
    command: gunicorn --log-file=- --bind 0.0.0.0:5000 -k flask_sockets.worker
      run:app wsgi
    depends_on:
      - "redis"
  worker:
    build: ./web
    env_file: ./web/.env
    #command: rq worker --url redis://h:p75baf77e33e20554a633cbc382c96f04963833841ce5ef3ace0162e364594542@ec2-52-21-234-22.compute-1.amazonaws.com:26949 high default low
    command: python3 worker.py
    depends_on:
      - "redis"
    # volumes:
    #   - ./web:/web
    # dashboard:
    #   build: ./web
    #   env_file: ./web/.env
    #   ports:
    #     - "9181:9181"
    #   command: rq-dashboard
    #   depends_on:
    #     - "redis"
  redis:
    image: redis:latest
    container_name: birbsredis
    command: sh -c "rm -f /data/dump.rdb && redis-server" # disable persistence
    ports:
      - "6379:6379"
  clock:
    build: ./web
    env_file: ./web/.env
    command: python3 clock.py
    depends_on:
      - "redis"
